# Generated by Django 5.0.3 on 2024-03-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ_donation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='contact_number',
            field=models.CharField(default=1234567, max_length=15),
            preserve_default=False,
        ),
    ]
