# Generated by Django 5.0.3 on 2024-03-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ_donation_app', '0002_donor_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='donor',
            name='contact_number',
            field=models.CharField(default='1234567890', max_length=15),
        ),
    ]
