# Generated by Django 5.0.3 on 2024-03-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ_donation_app', '0003_donor_email_alter_donor_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='age',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='name',
        ),
        migrations.AddField(
            model_name='donor',
            name='addressOfDonor',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='ageOfDonor',
            field=models.IntegerField(default='50'),
        ),
        migrations.AddField(
            model_name='donor',
            name='bloodGrp',
            field=models.CharField(default='O+', max_length=5),
        ),
        migrations.AddField(
            model_name='donor',
            name='emailIdOfDonor',
            field=models.CharField(default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='donor',
            name='firstName',
            field=models.CharField(default='f_name', max_length=15),
        ),
        migrations.AddField(
            model_name='donor',
            name='genderOfDonor',
            field=models.CharField(default='Female', max_length=10),
        ),
        migrations.AddField(
            model_name='donor',
            name='lastName',
            field=models.CharField(default='l_name', max_length=15),
        ),
        migrations.AddField(
            model_name='donor',
            name='middleName',
            field=models.CharField(default='m_name', max_length=15),
        ),
        migrations.AlterField(
            model_name='donor',
            name='contact_number',
            field=models.CharField(default='1234567891', max_length=15),
        ),
        migrations.AlterField(
            model_name='donor',
            name='organ_to_donate',
            field=models.CharField(default='Heart', max_length=10),
        ),
    ]
