# Generated by Django 5.0.3 on 2024-03-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ_donation_app', '0004_remove_donor_age_remove_donor_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='organ_to_donate',
        ),
        migrations.AddField(
            model_name='donor',
            name='alcoholConsumptionStatus',
            field=models.CharField(default='Never', max_length=10),
        ),
        migrations.AddField(
            model_name='donor',
            name='allergyEntries',
            field=models.CharField(default='Nil', max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='medicalConditions',
            field=models.CharField(default='Nil', max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='medicationEntries',
            field=models.CharField(default='Nil', max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='previousSurgery',
            field=models.CharField(default='Nil', max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='smokingPercentage',
            field=models.IntegerField(default=0),
        ),
    ]
