# Generated by Django 5.0.3 on 2024-03-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ_donation_app', '0006_donor_organ_to_donate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='smokingPercentage',
        ),
        migrations.AddField(
            model_name='donor',
            name='smokingStatus',
            field=models.CharField(default='Never', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='alcoholConsumptionStatus',
            field=models.IntegerField(default=0),
        ),
    ]
