# Generated by Django 5.0.3 on 2024-03-09 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organ_donation_app', '0007_remove_donor_smokingpercentage_donor_smokingstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='alcoholConsumptionStatus',
        ),
    ]
